language: ruby
rvm:
  - 2.2
  - 2.1
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt56
  - sudo apt-get update
  - sudo apt-get install -y qt56base qt56declarative
before_script:
  - source /opt/qt56/bin/qt56-env.sh
  - cd ext/qml
  - bundle exec ruby extconf.rb
  - make
