language: ruby
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt521
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y g++-4.7 libffi-dev qt52base qt52declarative
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90
before_script:
  - source /opt/qt52/bin/qt52-env.sh
  - cd ext/qml
  - bundle exec ruby extconf.rb
  - make
